export const HANDLE_TEXT_INPUT_CHANGE = 'HANDLE_TEXT_INPUT_CHANGE';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
